### ISSUE TITLE
directory_to_streams fails with large directories

### ISSUE THREAD

**Issue by jrekoske-usgs** [usgs/groundmotion-processing#334]
Running directory_to_streams() on the Loma Prieta CESMD data fails with the error:

`Traceback (most recent call last):`
  `File "/Users/jrekoske/anaconda3/envs/gmprocess/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3296, in run_code`
  `File "<ipython-input-2-4f4cbf62d656>", line 1, in <module>
    streams = directory_to_streams('lomaprieta_17oct1989')`
  `File "/Users/jrekoske/Repositories/groundmotion-processing/gmprocess/io/read_directory.py", line 62, in directory_to_streams`
  `File "/Users/jrekoske/anaconda3/envs/gmprocess/lib/python3.7/shutil.py", line 513, in rmtree`
  `File "/Users/jrekoske/anaconda3/envs/gmprocess/lib/python3.7/shutil.py", line 374, in _rmtree_unsafe`
  `File "/Users/jrekoske/anaconda3/envs/gmprocess/lib/python3.7/shutil.py", line 371, in _rmtree_unsafe`
`OSError: [Errno 24] Too many open files: '/var/folders/kq/pptpfzfn2yngmh2wjkzwznb458ffr5/T/tmpjjlfkunv/directory_to_streams'`

To fix this, we may need to make sure that all file open() commands in the readers have corresponding close() commands. The data is primarily dmg and smc files.

**Comment by jrekoske-usgs** [comment]
This seems to be fixed, directory_to_streams no longer gives this error with Loma Prieta data. This also seems to work fine reading some of the Ridgecrest data where there are over 1000 streams, so it seems this can be closed.
