### ISSUE TITLE
Unknown network code?

### ISSUE THREAD

**Issue by emthompson-usgs** [usgs/groundmotion-processing#639]
For data with an unknown network code, we a re using "ZZ". But "ZZ" is a currently used network code. Should we change this to something that is unused like "00" or "99"?

**Comment by emthompson-usgs** [comment]
It would actually be nice to use something like "--" but I suspect that would not validate because it is supposed to be alphanumeric.

**Comment by jas82** [comment]
It looks like the decision was "--". It doesn't validate for me for the SouthNapa earthquake data when I run gmrecords assemble. This is the traceback

Traceback (most recent call last):
  File "/Users/jamesasmith/.conda/envs/gmprocess/bin/gmrecords", line 33, in <module>
    sys.exit(load_entry_point('gmprocess', 'console_scripts', 'gmrecords')())
  File "/Users/jamesasmith/Packages/groundmotion-processing/gmprocess/bin/gmrecords.py", line 6, in main
    GMrecordsApp().main()
  File "/Users/jamesasmith/Packages/groundmotion-processing/gmprocess/apps/gmrecords.py", line 90, in main
    self.args.func().main(self)
  File "/Users/jamesasmith/Packages/groundmotion-processing/gmprocess/subcommands/assemble.py", line 58, in main
    self._assemble_event(event)
  File "/Users/jamesasmith/Packages/groundmotion-processing/gmprocess/subcommands/assemble.py", line 84, in _assemble_event
    workspace, _, _, _ = download(
  File "/Users/jamesasmith/Packages/groundmotion-processing/gmprocess/io/fetch_utils.py", line 106, in download
    streams, bad, terrors = directory_to_streams(in_raw_dir)
  File "/Users/jamesasmith/Packages/groundmotion-processing/gmprocess/io/read_directory.py", line 56, in directory_to_streams
    streams += read_data(file_path)
  File "/Users/jamesasmith/Packages/groundmotion-processing/gmprocess/io/read.py", line 40, in read_data
    streams = read_method(filename, **kwargs)
  File "/Users/jamesasmith/Packages/groundmotion-processing/gmprocess/io/smc/core.py", line 192, in read_smc
    stats, num_comments = _get_header_info(
  File "/Users/jamesasmith/Packages/groundmotion-processing/gmprocess/io/smc/core.py", line 403, in _get_header_info
    raise BaseException(fmt % filename)
BaseException: SMC: Record found in file /var/folders/y9/prvx92xj1mvg268yxbgl09d0002mb8/T/tmpoql6xo4d/directory_to_streams/SouthNapa_24Aug2014_72282711_SouthNapa_24Aug2014_72282711_NP1829_southnapa_24aug2014_72282711_np1829r_1829.HNE.NP.--_u.smc has a problem flag!

If this isn't an easy fix ,maybe it's best to use 99 for an unknown network (if that validates).

**Comment by jas82** [comment]
I removed the previous comment, as I realized this was not related to the network code '--' but to an issue with SMC. I am able to get data with the '--' network from CESM.
